export const USER_TYPE = {
  GUEST: "guest",
  USER: "user",
  ADMIN: "admin",
};

export const FILE_TYPE = {
  IMAGE: "image",
  VIDEO: "video",
  AUDIO: "audio",
  DOCUMENT: "document",
};

export const EVENTS = {
  connection: "connection",
  CLIENT: {
    connect: "connect",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    DELETE_CONVERSATION: "DELETE_CONVERSATION",
    REQUEST_ROOM_MESSAGE: "REQUEST_ROOM_MESSAGE",
    REQUEST_CONTACT_LIST: "REQUEST_CONTACT_LIST",
    REQUEST_USER_LIST: "REQUEST_USER_LIST",
    JOIN_ROOM: "JOIN_ROOM",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    EDIT_MESSAGE: "EDIT_MESSAGE",
    TYPING: "TYPING",
    BLOCK: "BLOCK",
    FORWARD: "FORWARD",
    REQUEST_NOTIFICATION: "REQUEST_NOTIFICATION",
    MARK_READ_NOTIFICATION: "MARK_READ_NOTIFICATION",
    REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
  },
  SERVER: {
    JOINED_ROOM: "JOINED_ROOM",
    RECEIVE_ROOM_MESSAGE: "RECEIVE_ROOM_MESSAGE",
    DELETE_MESSAGE_RESULT: "DELETE_MESSAGE_RESULT",
    EDIT_MESSAGE_RESULT: "EDIT_MESSAGE_RESULT",
    DELETE_CONVERSATION_RESULT: "DELETE_CONVERSATION_RESULT",
    RECEIVE_CONTACT_LIST: "RECEIVE_CONTACT_LIST",
    RECEIVE_USER_LIST: "RECEIVE_USER_LIST",
    IS_TYPING: "IS_TYPING",
    BLOCK_RESULT: "BLOCK_RESULT",
    FORWARD_RESULT: "FORWARD_RESULT",
    RECEIVE_NOTIFICATION: "RECEIVE_NOTIFICATION",
    MARK_READ_NOTIFICATION_RESULT: "MARK_READ_NOTIFICATION_RESULT",
    REMOVE_NOTIFICATION_RESULT: "REMOVE_NOTIFICATION_RESULT",
    STATUS: {
      ONLINE: "ONLINE",
      OFFLINE: "OFFLINE",
    },
  },
};
